 
version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nispera
      MYSQL_USER: nispera_admin
      MYSQL_PASSWORD: 33qysqlsqsdemctqvclbqatmESTOPA
    volumes:
      - ./mysql/data:/var/lib/mysql
